# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3414016413fdacfb693c5c007c2ee98ec2f10e32c96382b179761e98d18007df4924cb4ab989a89ec3d2c96438172c114ef30939e9d29daf4bd975542690dcf7
  host: 'http://localhost:3000'

test:
  secret_key_base: 5b9c975573cb639949a953903288788ddfa9804129ea272c76fae881ff05f626538d2074aab1944d8c7e27aeefd3fec77742f00e7e51c18450ca728a3ec1aee5
  host: 'http://staging.com:3000'

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  host: 'http://production.com:3000'
